config/routes.rb
Etsydemo::Application.routes.draw do

  root "listings#index"

  get "about" => "pages#about"
  get "contact" => "pages#contact"
  
  devise_for :users

  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'my_listings' => "listings#my_listings"

  get 'purchases' => "orders#purchases"
  get 'sales' => "orders#sales" 

  

  

end

app/models/listing.rb
class Listing < ActiveRecord::Base
	if Rails.env.development?
		has_attached_file :image, 
											:styles => { :medium => "200x", :thumb => "100x100>" }, 
											:default_url => "default.png"
	else
		has_attached_file :image, 
											:styles => { :medium => "200x", :thumb => "100x100>" }, 
											:default_url => "default.png",
      								:storage => :dropbox,
      								:dropbox_credentials => Rails.root.join("config/dropbox.yml"),
      								:path => ":style/:id_:filename"
	end

	validates :name, :description, :price,
						presence: true
	validates :price, numericality: {greater_than: 0}
	#round to cents.				
	validates_attachment_presence :image
	
	belongs_to :user
	has_many :orders
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # Require authentication before going to these pages.
  before_filter :authenticate_user!, only: [:my_listings, :new, :create, :edit, :update, :destroy]
  # Require the authentication matches for the listing.
  # Doesn't require :my_listings because the path for my_listings is defined with current_user.
  before_filter :check_user, only: [:edit, :update, :destroy]

  # GET /listings
  # GET /listings.json

  def my_listings
    @listings = Listing.where(user: current_user).order("created_at DESC")
  end

  def index
    @listings = Listing.all.order("created_at DESC")
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
    @listing = Listing.find(params[:id])
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit

  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)
    @listing.user_id = current_user.id
    #what if not logged in; what does current_user return?
    
    if current_user.recipient.blank?
      Stripe.api_key = ENV["STRIPE_API_KEY"]
      token = params[:stripeToken]

      recipient = Stripe::Recipient.create(
        :name => current_user.username,
        :type => "individual",
        :bank_account => token
        )
    end

    current_user.recipient = recipient.id
    current_user.save

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
        format.json { render action: 'show', status: :created, location: @listing }
      else
        format.html { render action: 'new' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @listing.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :description, :price, :image)
    end

    def check_user
      if (current_user != @listing.user)
        # Make this an alert instead, so that it says on the existing current page.
        # Will an alert be visible if user is in scrolled low position?
        redirect_to root_url, alert: "Sorry, this listing belongs to someone else"
      end      
    end
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/_form.html.erb
<%= form_for @listing, :html => { :multipart => true } do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h4><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h4>
      <ul>
      <% @listing.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div id="stripe_error" class="alert alert-danger" style="display:none">
    <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
  </div>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :price %><br>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.file_field :image %>
  </div>

  <br>

  <% if current_user.recipient.blank? %>  
    <h1>Bank Account Information</h1>
    <%# How to get this portion as a first time thing %>

    <div class="form-group">
      <%= label_tag      :country %><br>
      <%= text_field_tag :country, nil, { :name => nil, :'data-stripe' => "country", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= label_tag      :routing_number %><br>
      <%= text_field_tag :routing_number, nil, { :name => nil, :'data-stripe' => "routingNumber", class: "form-control" } %>
    </div>
    <div class="form-group">
      <%= label_tag      :account_number %><br>
      <%= text_field_tag :account_number, nil, { :name => nil, :'data-stripe' => "accountNumber", class: "form-control" } %>
    </div>

    <div class="actions form-group">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  <% end %>
<% end %>

app/views/listings/edit.html.erb
<h1>Editing listing</h1>

<%= render 'form' %>
<%= link_to 'Destroy', @listing, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default btn-danger" %>

<%= link_to 'Back to Listing', @listing, class: "btn btn-link" %> |
<%= link_to 'All Listings', listings_path, class: "btn btn-link" %>

app/views/listings/index.html.erb
<div class="jumbotron">
  <h1>Handcrafted items from around the world.</h1><br>
  <h2>Discover one-of-a-kind items</h2>
</div>

<div class="center">
  <div class="row">

    <% @listings.each do |listing| %>
      <div class="col-sm-3">
        <div class="thumbnail">
          <%= link_to image_tag(listing.image.url), listing %>
          <div class="caption">
            <h3><%= link_to listing.name, listing %></h3>
            <p><%= number_to_currency(listing.price) %></p>
            <p><%= "Sold by " %><%= link_to "#{listing.user.username}", root_url %><%#=listing.user%></p>            
            <% if (user_signed_in?) && (current_user == listing.user) %>
              <%= link_to 'Edit', edit_listing_path(listing), class: "btn btn-link" %>              
            <% end %>
          </div>
        </div>
      </div>
    <% end %>

  </div>
</div>

<%# devise controls %>
<% if (user_signed_in?) %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true }  %>
<% end %>

app/views/listings/my_listings.html.erb
<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Name</th>
    <th class="center">Description</th>
    <th class="center">Price</th>
    <th class="center">Action</th>
  </tr>

  <% @listings.each do |listing| %>
    <tr>
      <td><%= image_tag listing.image.url(:thumb) %></td>
      <td><%= listing.name %></td>
      <td><%= listing.description %></td>
      <td><%= number_to_currency(listing.price) %></td>
      <td>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", listing, class: "btn btn-link" %></li>
            <li><%= link_to "Edit", edit_listing_path(listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<br>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true }  %>
<% end %>

app/views/listings/new.html.erb
<h1>New listing</h1>

<%= render 'form' %>

<%= link_to 'Back', listings_path, class: "btn btn-link" %>

app/views/listings/show.html.erb
<div class="row">
	<div class="col-md-6">
		<div class="thumbnail">
			<%= image_tag @listing.image.url %>
		</div>
	</div>
	<div class="col-md-6">
  	<h3><%= @listing.name %></h3>
  	<% if (user_signed_in?) && (current_user == @listing.user) %>
  		<%= link_to "Edit", edit_listing_path(@listing), class: "btn btn-link"  %>
  	<% end %>
  	<div class="center">
  		<%= link_to "Buy", new_listing_order_path(@listing), class: "btn btn-primary", data: { no_turbolink: true } %>
  	</div>
  	<p><%= number_to_currency(@listing.price) %></p>
  	<p><%= @listing.description %></p>
  	<p><%= "Sold by " %><%= link_to "#{@listing.user.username}", root_url %></p>
	</div>
</div>

<% if (user_signed_in?) && (current_user == @listing.user) %>
	<%= link_to 'Edit', edit_listing_path(@listing), class: "btn btn-link" %> |
<% end %>
<%= link_to 'Back to Listings', listings_path, class: "btn btn-link" %>