config/routes.rb
Etsydemo::Application.routes.draw do

  root "listings#index"

  get "about" => "pages#about"
  get "contact" => "pages#contact"
  
  devise_for :users

  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'my_listings' => "listings#my_listings"

  get 'purchases' => "orders#purchases"
  get 'sales' => "orders#sales" 

  

  

end

app/models/order.rb
class Order < ActiveRecord::Base
	validates :address, :city, :state, presence: true		
	validates :listing_id, :buyer_id, :seller_id, presence: true
	#validates :seller_id, :current_id, uniqueness: true

	belongs_to :listing
	belongs_to :buyer,  class_name: "User"
	belongs_to :seller, class_name: "User"
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def purchases
    @orders = Order.all.where(buyer: current_user).order("created_at DESC")    
  end
  
  def sales
    @orders = Order.all.where(seller: current_user).order("created_at DESC")
  end

  # GET /orders
  # GET /orders.json


  # GET /orders/1
  # GET /orders/1.json

  # GET /orders/new
  def new
    @order = Order.new
    @listing = Listing.find(params[:listing_id])
  end


  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    @listing = Listing.find(params[:listing_id])
    @seller = @listing.user

    @order.listing_id = @listing.id
    @order.buyer_id = current_user.id
    @order.seller_id = @seller.id

    Stripe.api_key = ENV["STRIPE_API_KEY"]
    token = params[:stripeToken]

    begin
      charge = Stripe::Charge.create(
        :amount => (@listing.price * 100).floor,
        :currency => "usd",
        :card => token
        )
      flash[:notice] = "Thankyou for ordering!"
    rescue Stripe::CardError => e
      flash[:danger] = e.message
    end

    retained = 95

    transfer = Stripe::Transfer.create(
      :amount => (@listing.price*retained).floor,
      :currency => "usd",
      :recipient => @seller.recipient
      )

    respond_to do |format|
      if @order.save
        # change to redirect to previously viewed page. How to get history page buffer?
        format.html { redirect_to root_url }
        format.json { render action: 'show', status: :created, location: @order }
      else
        format.html { render action: 'new' }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:address, :city, :state)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<div class="row">
  <div class="col-xs-4">
    <div class="thumbnail">
      <%= image_tag @listing.image.url %>
    </div>
    <h3><%= @listing.name %></h3>
    <h4><%= number_to_currency(@listing.price) %></h4>
  </div>

  <div class="col-xs-8">    
    <%= form_for([ @listing, @order ]) do |f| %>
      <% if @order.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

          <ul>
          <% @order.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div id="stripe_error" class="alert alert-danger" style="display:none">
        <noscript>JavaScript is not enabled and is required for this form. First enable it in your web browser settings.</noscript>
      </div>

      <div class="form-group">
        <%= label_tag nil, "Expiration Date" %>
        <div class="row">
          <div class="col-xs-8">
            <%= label_tag :card_number %><br>
            <%= text_field_tag :card_number, nil, { :name => nil, :'data-stripe' => "number", class: "form-control" } %>
          </div>
          <div class="col-xs-4">
            <%= label_tag :card_code, "CVC" %><br>
            <%= text_field_tag :card_code, nil, { :name => nil, :'data-stripe' => "cvc", class: "form-control" } %>
          </div>
        </div>
      </div>

      <div class="form-group">
        <div class="row">
          <div class="col-xs-3">
          <%= select_month nil, { use_two_digit_numbers: true }, { :name => nil, :'data-stripe' => "exp-month", class: "form-control" } %>
          </div>
          <div class="col-xs-3">
          <%= select_year nil, { start_year: Date.today.year, end_year: Date.today.year+10 }, { :name => nil, :'data-stripe' => "exp-year", class: "form-control" } %>
          </div>
        </div>
      </div>
      
      <div class="form-group">
        <%= f.label :address %><br>
        <%= f.text_field :address, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :city %><br>
        <%= f.text_field :city, class: "form-control" %>
      </div>
      <div class="form-group">
        <%= f.label :state %><br>
        <%= f.text_field :state, class: "form-control" %>
      </div>

      <div class="actions form-group">
        <%= f.submit "Complete Order", class: "btn btn-primary btn-btn-success" %>
 
      </div>
    <% end %>
  </div>
</div>

app/views/orders/new.html.erb
<%= render 'form' %>

<%= link_to 'Back to Listings', listing_orders_path %>

app/views/orders/purchases.html.erb
<div class="center">
<h2> Your Purchase History </h2>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Seller</th>
    <th class="center">Date Purchased</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td><%= image_tag order.listing.image.url(:thumb) %></td>
      <td><%= order.listing.name %></td>
      <td><%= number_to_currency(order.listing.price) %></td>
      <td><%= order.seller.username %></td>
      <td><%= order.created_at.strftime("%^b %d, %Y") %>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", order.listing, class: "btn btn-link" %></li>
            <li><%#= link_to "Edit", edit_listing_path(order.listing), class: "btn btn-link" %></li>
            <li><%#= link_to 'Destroy', order.listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>
<br>
<div>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true }  %>
<% end %>


app/views/orders/sales.html.erb
<div class="center">
<h2> Your Sales History </h2>

<table class="table table-striped table-bordered">
  <tr>
    <th class="center">Image</th>
    <th class="center">Item</th>
    <th class="center">Price</th>
    <th class="center">Customer</th>
    <th class="center">Date Sold</th>
  </tr>

  <% @orders.each do |order| %>
    <tr>
      <td><%= image_tag order.listing.image.url(:thumb) %></td>
      <td><%= order.listing.name %></td>
      <td><%= number_to_currency(order.listing.price) %></td>
      <td><%= order.buyer.username %></td>
      <td><%= order.created_at.strftime("%^b %d, %Y") %>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
            Action <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "View", order.listing, class: "btn btn-link" %></li>
            <li><%#= link_to "Edit", edit_listing_path(order.listing), class: "btn btn-link" %></li>
            <li><%= link_to 'Destroy', order.listing, method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-link" %></li>
          </ul>
        </div>
      </td>
    </tr>
  <% end %>
</table>

<br>
<div>

<% if user_signed_in? %>
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-link", data: { no_turbolink: true }  %>
<% end %>


app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<p>
  <strong>City:</strong>
  <%= @order.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @order.state %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>