config/routes.rb
Etsydemo::Application.routes.draw do

  root "listings#index"

  get "about" => "pages#about"
  get "contact" => "pages#contact"
  
  devise_for :users

  resources :listings do
    resources :orders, only: [:new, :create]
  end

  get 'my_listings' => "listings#my_listings"

  get 'purchases' => "orders#purchases"
  get 'sales' => "orders#sales" 

  

  

end

app/views/layouts/_footer.html.erb
<footer>
</footer>

app/views/layouts/_header.html.erb
<header>
</header>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">

  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Etsydemo", root_path, :class=>"navbar-brand" %>
      <!--
      <a class="navbar-brand" href="/">EtsyDemo</a>
      -->
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><%= link_to "Contact", contact_path %></li>        
        <li><%= link_to "About",     about_path %></li>        
      </ul>

      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>

      <ul class="nav navbar-nav navbar-right">
      <% if !user_signed_in? %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <%# registering by picking username only, at first. check if available. let them use, comment, etc. Allow full registration button if click manually. But also, if they don't, before they navigate away, popup with form, saying "don't let the fun go to waste!" shows temporarily claimed username, warn "otherwise, it will be freed for others to take", email field, pw, pwconfirm. %>
        <li><%= link_to "Log In", new_user_session_path %></li>       
      <% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.username %> <b class="caret"></b></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Add New Listing", new_listing_path %></li>
            <li class="divider"></li>
            <li><%= link_to "My Listings", my_listings_path %></li>
            <li><%= link_to "Purchase History", purchases_path %></li>
            <li><%= link_to "Sales History", sales_path %></li>
            <li class="divider"></li>            
            <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          </ul>
        </li>
        <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>        
      <% end %>
              
      </ul>

    </div>
  </div>

</nav>

app/views/layouts/_sidebar.html.erb
<aside>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>Etsydemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "https://js.stripe.com/v2/" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => ENV["STRIPE_PUBLIC_KEY"] %>
</head>

<body>

<%= render 'layouts/header' %>

<div class="container">	
	<%= render 'layouts/navbar' %>
  <%= render 'layouts/sidebar' %>

	<% flash.each do |name, msg| %>
    <% if msg.is_a?(String) %>
      <div class="alert alert-<%= name == :notice ? "success" : "danger" %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        <%= content_tag :div, msg, :id => "flash_#{name}" %>
      </div>
    <% end %>
  <% end %>

	<!--<p class="alert"><%= alert %></p>
	-->

	<%= yield %>
</div>

<%= render 'layouts/footer' %>

</body>
</html>